"""empty message

Revision ID: 05e706dcf54a
Revises: 65f2c30e0fdc
Create Date: 2019-01-27 16:20:14.139405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e706dcf54a'
down_revision = '65f2c30e0fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('subject', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'subject')
    # ### end Alembic commands ###
